feat ✨ add gh action to send out reminder about upcoming meetings
FreifunkMD/.github pull request #28
Opened 2023-04-19 20:06 UTC by 24367dfa

closes #23 

https://github.com/caronc/apprise/wiki/Notify_discord
https://github.com/caronc/apprise/wiki/Notify_email
https://github.com/caronc/apprise/wiki/Notify_twitter
https://github.com/caronc/apprise/wiki/Notify_mastodon

2023-04-20 08:35 UTC, penguineer requested changes

2023-04-20 08:35 UTC, penguineer commented on .github/workflows/meeting-reminder.yaml
> +  message: "Wir treffen uns ab 19:30 in den Räumen des Netz39 e.V."
Wie wäre es mit:
"Das nächste Freifunk-Treffen findet am kommenden Montag um 19:30 Uhr in den Räumen des Netz39 e.V. statt."?

Es gibt unterschiedliche Interpretationen für "nächster" und manche MUAs stellen den Betreff sehr weit weg vom Body dar, sodass es ganz gut ist, die Nachricht self-contained zu machen.

2023-04-20 08:35 UTC, penguineer commented on .github/workflows/meeting-reminder.yaml
> +    cron: 1 0 11-17 * 5
Bislang habe  ich die Reminder Donnerstags verschickt, damit man noch einen Wochentag mehr für die Planung/Erinnerung hat.

2023-04-20 08:40 UTC, penguineer commented
Auf den unterschiedlichen Medien gibt es unterschiedliche an die Form der Nachricht. 
Wie wäre es, eine Rahmen-Action zu haben, die den Zeitpunkt festlegt und dann Sub-Actions für 
* E-Mail
* Twitter/Mastodon
* Discord
zu haben, die dann die jeweiligen Texte enthalten?
Oder man  ruft die Apprise-Action einfach in der bestehenden Action dreimal mit den entsprechenden Texten auf.

2023-04-20 08:41 UTC, penguineer commented
Letzte Erinnerungsmail:
```
Subject: Freifunk-Treffen am 17.04.2023

Liebe Freifunk-Interessent:innen,

unser nächstes Treffen findet am 17.04.2023 um 19:30 Uhr in den Räumen
des Netz39 e.V. (Leibnizstr. 32) statt.


In den Netz39-Räumen gilt die 2G-Regel. Zum Schutz aller möchte ich euch
bitten, einen nicht allzu alten Test zu haben (ideal natürlich recht direkt
vor der Veranstaltung).


Falls ihr hybrid teilnehmen möchtet, gebt mir bitte bis 2h vorher kurz
Bescheid, dann kümmere ich mich um die Online-Variante.


Viele Grüße,
Stefan
```

2023-04-20 08:42 UTC, penguineer commented
Letzter Tweet/Tröt:
```
Morgen (Montag, 17.04.) ist unser nächstes Freifunk-Treffen, um 19:30 Uhr in den Räumen  des Netz39 e.V. in der Leibnizstr. 32!
```

2023-04-20 08:43 UTC, penguineer commented
Das Datum mit im Text zu haben wäre toll, weil das wesentlich eindeutiger ist.

2023-04-20 19:37 UTC, 24367dfa commented
> Das Datum mit im Text zu haben wäre toll, weil das wesentlich eindeutiger ist. Das kann aber auch eine Ergänzung in einem späteren PR sein.

yep. erstmal den MVP :P

2023-04-21 08:43 UTC, penguineer approved these changes
Ich habe noch etwas gefunden, das wir verbessern sollten (Version Pinning), ansonsten sieht das erstmal gut aus.

Approve, weil es nicht blocking ist, aber kann das vor dem  Merge noch behoben werden. (Ich bin am WE unterwegs.)

2023-04-21 08:43 UTC, penguineer commented on .github/workflows/meeting-reminder.yaml
> +uses: cstuder/apprise-ga@master
Kannst Du hier bitte statt auf `master` auf eine Version pinnen?
`v3.0.1` ist gerade aktuell.

2023-04-21 08:43 UTC, penguineer commented on .github/workflows/meeting-reminder.yaml
> +uses: cstuder/apprise-ga@master
Kannst Du hier bitte statt auf `master` auf eine Version pinnen?
`v3.0.1` ist gerade aktuell.

2023-04-21 11:34 UTC, 24367dfa commented on .github/workflows/meeting-reminder.yaml
> +uses: cstuder/apprise-ga@master
/done

2023-04-21 11:35 UTC, 24367dfa commented on .github/workflows/meeting-reminder.yaml
> +uses: cstuder/apprise-ga@master
/done

2023-04-21 11:35 UTC, merged